blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from .import views

app_name ='blogs'

urlpatterns =[
  #Home page
  path('',views.index, name='index'),
  #Page that shows all blog posts
  path('blogposts/',views.blog_posts,name = 'blog_posts'),
  #page that displays a single blog post
  path('blogposts/<int:blog_post_id>/',views.blog_post,name = 'blog_post'),
  #page for adding a new blog post
  path('newblogpost/', views.new_blog_post,name='new_blog_post'),
  #page for editing single blog post
  path('blogposts/<int:blog_post_id>/editblogpost/',views.edit_blog_post,name = 'edit_blog_post'),
  #page for deleting single blog post
  path('blogposts/<int:blog_post_id>/deleteblogpost/',views.delete_blog_post,name = 'delete_blog_post'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path,include

from .import views

app_name='users'
urlpatterns =[
    #include default auth urls.
    path('',include ('django.contrib.auth.urls')),
    #Registration page.
    path('register/',views.register,name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    """For adding new blog posts"""
    title= models.CharField(max_length = 200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    public = models.BooleanField(default=False)


    def __str__(self):
        """Return a string representation of the model."""
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title':'','text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

class DeleteForm(forms.ModelForm):
  class Meta:
      model = BlogPost
      fields =[]

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm
from .forms import DeleteForm
# Create your views here.

def index(request):
    """The home page for Blog"""
    return render(request,'blogs/index.html')

def blog_posts(request):
    """Show all blog posts."""
    if request.user.is_authenticated:
        blogposts1 = BlogPost.objects.filter(owner=request.user)
        blogposts2 = BlogPost.objects.filter(public=True)
        blog_posts = blogposts1.union(blogposts2).order_by('date_added')
    else: 
        blog_posts = BlogPost.objects.filter(public=True)
    context = {'blog_posts':blog_posts}
    return render(request, 'blogs/blog_posts.html',context)

def check_blog_post_public(request,blog_post_id):
    """check if the blogpost can be viewed by all users"""
    blog_post = BlogPost.objects.get(id=blog_post_id)
    if blog_post.public==False:
        check_blog_post_owner(request, blog_post_id)
    

def check_blog_post_owner(request,blog_post_id):
    """check if blog_post owner matches current user"""
    blog_post = BlogPost.objects.get(id=blog_post_id)
    if blog_post.owner != request.user:
        raise Http404 


def blog_post(request, blog_post_id):
    """Show a single blog post"""
    blog_post = get_object_or_404(BlogPost,id = blog_post_id)
    #make sure the blog post belongs to the current user.
    check_blog_post_public(request,blog_post_id)
    blog_content=blog_post.text
    context = {'blog_post':blog_post, 'blog_content':blog_content}
    return render(request, 'blogs/blog_post.html',context)

@login_required
def new_blog_post(request):
    """Add a new blog post."""
    if request.method !='POST':
        #no data submitted; create a blank form.
        form = BlogPostForm()
    else:
        #POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_blog_post=form.save(commit=False)
            new_blog_post.owner=request.user
            switch1 = request.POST.get('tog')
            if switch1 =="on":
                new_blog_post.public = True
            else:
                new_blog_post.public = False
            new_blog_post.save()
            return redirect('blogs:blog_posts')

    #display a blank or invalid form. 
    context= {'form':form}
    return render(request, 'blogs/new_blog_post.html',context)

@login_required
def edit_blog_post(request,blog_post_id):
    """Edit an existing blog post"""
    blog_post = BlogPost.objects.get(id=blog_post_id)
    if request.method !='POST':
        check_blog_post_owner(request,blog_post_id)
        #initial request; pre-fill form with the current entry
        form = BlogPostForm(instance = blog_post)
    else:
        check_blog_post_owner(request,blog_post_id)
        #POST data submitted; process data.
        form = BlogPostForm(instance=blog_post, data=request.POST)
        if form.is_valid():
            edit_blog_post=form.save(commit=False)
            edit_switch1 = request.POST.get('edit_tog')
            if edit_switch1 =="on":
                edit_blog_post.public = True
            else:
                edit_blog_post.public = False
            edit_blog_post.save()
            return redirect('blogs:blog_post',blog_post_id= blog_post.id)
    context = {'blog_post':blog_post,'form':form}
    return render(request, 'blogs/edit_blog_post.html',context)

@login_required
def delete_blog_post(request,blog_post_id):
    """Delete an existing blog post"""
    blog_post = get_object_or_404(BlogPost,id = blog_post_id)
    if request.method =='POST':
        check_blog_post_owner(request,blog_post_id)
        form=DeleteForm(request.POST)
        if form.is_valid():
            #confirm delete
            blog_post.delete()
            return redirect('blogs:blog_posts')
    context = {'blog_post':blog_post}
    return render(request, 'blogs/delete_blog_post.html',context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method !='POST':
        #Display blank registration form.
        form = UserCreationForm()
    else:
        #process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log the user in and then redirect to home page.
            login(request,new_user)
            return redirect('blogs:index')

    #display a blank or invalid form.
    context={'form':form}
    return render(request,'registration/register.html',context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang ="en">
  <head>
    <meta charset ="utf-8">
    <meta name = "viewport" content="width=device-width,initial-scale=1,
    shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'blogs:index'%}">
      Home Page</a>
    <button class = "navbar-toggler" type="button" data-toggle = "collapse"
    data-target = "#navbarCollapse" aria-controls = "navbarCollapse"
    aria-expanded = "false" aria-label ="Toggle navigation">
    <span class = "navbar-toggle-icon"></span></button>
    <div class = "collapse navbar-collapse" id = "navbarCollapse">
      <ul class = "navbar-nav mr-auto">
        <li class = "nav-item">
          <a class = "nav-link" href ="{% url 'blogs:blog_posts'%}">
            Blog Posts</a></li>
      </ul>
      <ul class = "navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class ="nav-item">
          <span class = "navbar-text">Hello, {{user.username}}.</span>
        </li>
        <li class = "nav-item">
          <a class = "nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class = "nav-item">
          <a class = "nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class = "nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>
    </nav>
    <main role ="main" class ="container">
      <div class ="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
  </body>

</html>

blogs/templates/blogs/blog_post.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h3>{{blog_post}}</h3>
<h6>Written by {{blog_post.owner}}</h6>
{% endblock page_header %}

{% block content %}

<div class ="card mb-3">
  <h4 class ="card-header">
  {{blog_post.date_added|date:'M d, Y H:i'}}
  <small><a href="{% url 'blogs:edit_blog_post' blog_post.id %}">Edit blog post</a></small>
  </h4>
  <div class="card-body">
    {{blog_content|linebreaks}}
  </div>
  <div class="card-footer" style= "text-align:right"><small><a href="{% url 'blogs:delete_blog_post' blog_post.id %}" style= "color:red">Delete blog post</a></small></div>
</div>
{% endblock content %}

blogs/templates/blogs/blog_posts.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h1>Blog Posts</h1>
{% endblock page_header %}

{% block content %}

<ul>
  {% for blog_post in blog_posts %}
  <li><h3>
    <a href="{% url 'blogs:blog_post' blog_post.id %}">{{blog_post}}</a> 
    {% if blog_post.public %}
      (public)
    {% else %}
      (private)
    {% endif %}
  </h3></li>
  {% empty %}
  <li><h3>No blog posts have been added yet</h3></li>
  {% endfor %}
</ul>

<h3><a href = "{% url 'blogs:new_blog_post' %}">Add a new blog post</a></h3>
{% endblock content %}

blogs/templates/blogs/delete_blog_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3>Delete blog post: "{{blog_post}}"</h3> 
{% endblock page_header %}

{% block content %}

<form action = "{% url 'blogs:delete_blog_post' blog_post.id %}" method = 'post' class="form">
  {% csrf_token %}
  <h4>Do you want to delete this post</h4>
  <p> </p>
 
  <p><input type = "submit" value = "Yes"/>   <a href= "../">Cancel</a></p>
</form>

{% endblock content %}

blogs/templates/blogs/edit_blog_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3>Edit blog post:</h3>
{% endblock page_header %}

{% block content %}

<p><h3><a href="{% url 'blogs:blog_post' blog_post.id %}">{{blog_post}}</a></h3></p>

<form action = "{% url 'blogs:edit_blog_post' blog_post.id %}" method = 'post' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="custom-control custom-switch">
    {% if blog_post.public %}
      <input type="checkbox" class="custom-control-input" id="edit_switch1" name="edit_tog" checked>
      <label class="custom-control-label" for="edit_switch1">Public</label>
    {% else %}
      <input type="checkbox" class="custom-control-input" id="edit_switch1" name="edit_tog" unchecked>
      <label class="custom-control-label" for="edit_switch1">Public</label>
    {% endif %}
  </div>
  <p>  </p>
  {% buttons %}
  <button name = "submit" class="btn btn-primary"> Save changes</button>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
<div class="jumbotron">
  <h1 class = "display-3">Blogs for All</h1>

<p class="lead">This blog allows users to write about any subject they want.</p>

<a class = "btn btn-lg btn-primary" href="{% url 'users:register' %}"
role="button">Register &raquo;</a>
<p><h6>Or explore the <a href ="{% url 'blogs:blog_posts'%}">
  Blog Posts</a> available to public</h6></p>
</div>
{% endblock page_header %}

blogs/templates/blogs/new_blog_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3>Add a new blog post:</h3>
{% endblock page_header %}

{% block content %}

<p>(Add blog title in first block and then add blog content in the block underneath)</p>
<p>  </p>

<form action = "{% url 'blogs:new_blog_post' %}" method = 'post' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="custom-control custom-switch">
    <input type="checkbox" class="custom-control-input" id="switch1" name="tog" unchecked >
    <label class="custom-control-label" for="switch1">Public</label>
  </div>
  <p>  </p>
  {% buttons %}
  <button name = "submit" class="btn btn-primary">Add blog post</button>
  {% endbuttons %}
</form>

{% endblock content %}